-- AlterTable
ALTER TABLE "payments" ADD COLUMN     "bonus_stars" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "settings" ADD COLUMN     "bonus_payment_1000" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
ADD COLUMN     "bonus_payment_10000" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
ADD COLUMN     "bonus_payment_20000" DOUBLE PRECISION NOT NULL DEFAULT 0.20,
ADD COLUMN     "bonus_payment_250" DOUBLE PRECISION NOT NULL DEFAULT 0.01,
ADD COLUMN     "bonus_payment_2500" DOUBLE PRECISION NOT NULL DEFAULT 0.07,
ADD COLUMN     "bonus_payment_500" DOUBLE PRECISION NOT NULL DEFAULT 0.03,
ADD COLUMN     "bonus_payment_5000" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
ADD COLUMN     "bonus_payment_50000" DOUBLE PRECISION NOT NULL DEFAULT 0.25;
