export enum EventType {
  REGISTRATION = 'REGISTRATION',
  ACTIVATION = 'ACTIVATION',
  FIRST_PAYMENT = 'FIRST_PAYMENT',
  RELOAD_PAYMENT = 'RELOAD_PAYMENT',
  WEEK_SUB = 'WEEK_SUB',
  REACTIVATION = 'REACTIVATION',
}
