global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Если позже добавишь alertmanager, вернёшь это
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: prometheus

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:4000']
        labels:
          service: api

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: postgres

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
        labels:
          service: redis

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: cadvisor

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: node

  - job_name: 'marzban'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - '/etc/prometheus/marzban_targets.yml'

  - job_name: 'xray-checker'
    metrics_path: '/metrics'
    basic_auth:
      username: 'metricsUser'
      password: 'MetricsVeryHardPassword'
    static_configs:
      - targets: ['localhost:2112']
