/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
import { Path } from 'nestjs-i18n'

export type I18nTranslations = {
  telegraf: {
    start: {
      welcome: string
    }
  }
  subscription: {
    created: string
    period: {
      trial_with_days: string
    }
  }
  referral: {
    defaultName: string
    rewardReceived: string
  }
  time: {
    days: {
      '1': string
      '2': string
      '3': string
      '4': string
      '5': string
      other: string
    }
  }
  payments: {
    payment_failed: string
    payment_success: string
    invoice: {
      title: string
      description: string
    }
    referral: {
      reward_title: string
      hold_reward: string
      available_reward: string
      referral_label: string
      level_label: string
    }
  }
  'subscription.renewed': string
  'subscription.renewal_failed_balance': string
  'subscription.deactivated': string
  'subscription.expiration_reminder': string
  'subscription.expiration_reminder_low_balance': string
  'time.days.0': string
  'time.days.1': string
  'time.days.2': string
}
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
