/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "payments": {
        "invoice": {
            "title": string;
            "description": string;
        };
        "payment_success": string;
        "payment_failed": string;
        "payment_expired": string;
        "referral": {
            "reward_title": string;
            "hold_reward": string;
            "available_reward": string;
            "referral_label": string;
            "level_label": string;
        };
        "hold": {
            "released": string;
        };
    };
    "referral": {
        "rewardReceived": string;
        "defaultName": string;
    };
    "subscription": {
        "deleted": string;
        "deleted_auto": string;
        "created": string;
        "period": {
            "hour": string;
            "day": string;
            "month": string;
            "three_month": string;
            "six_month": string;
            "year": string;
            "two_year": string;
            "three_year": string;
            "trial": string;
            "trial_with_days": string;
        };
        "renewed": string;
        "renewed_user": string;
        "renewal_failed_balance": string;
        "deactivated": string;
        "expiration_reminder": string;
        "expiration_reminder_low_balance": string;
        "token_reset": string;
        "auto_renewal_enabled": string;
        "auto_renewal_disabled": string;
    };
    "subscriptions": {
        "purchase": {
            "success": string;
            "failed": string;
            "insufficient_balance": string;
            "subscription_limit_exceeded": string;
            "user_not_found": string;
        };
        "free_plan": {
            "activated": string;
            "failed": string;
            "not_available": string;
        };
        "auto_renewal": {
            "enabled": string;
            "disabled": string;
            "success": string;
            "failed": string;
            "insufficient_balance": string;
        };
        "expiration": {
            "notification": string;
            "expired": string;
        };
    };
    "telegraf": {
        "start": {
            "welcome": string;
            "TOO_MANY_REQUESTS": string;
        };
    };
    "time": {
        "days": {
            "0": string;
            "1": string;
            "2": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
