export enum TransactionReasonEnum {
  WITHDRAWAL = 'WITHDRAWAL',
  PAYMENT = 'PAYMENT',
  SYSTEM = 'SYSTEM',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  REWARD = 'REWARD',
  REFERRAL = 'REFERRAL',
  FINE = 'FINE',
  EXCHANGE = 'EXCHANGE',
  GAME = 'GAME',
  BONUS = 'BONUS',
}
