export enum TransactionReasonEnum {
  WITHDRAWAL = 'WITHDRAWAL',
  PAYMENT = 'PAYMENT',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  REWARD = 'REWARD',
  REFERRAL = 'REFERRAL',
  FINE = 'FINE',
  EXCHANGE = 'EXCHANGE',
  GAME = 'GAME',
}
