export enum PaymentTypeEnum {
  PAY_SUBSCRIPTION = 'PAY_SUBSCRIPTION',
  UPDATE_SUBSCTIPTION = 'UPDATE_SUBSCTIPTION',
  ADD_TRAFFIC_SUBSCRIPTION = 'ADD_TRAFFIC_SUBSCRIPTION',
  ADD_PAYMENT_BALANCE = 'ADD_PAYMENT_BALANCE',
}
